name: Deploy-CN
on:
  push:
    branches:
      - main-cn
  pull_request_target:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run 'cabal update; make html'
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: master
          folder: _build/html
          repository-name: July541/July541.github.io
          target-folder: hoh
          token: ${{ secrets.TOKEN }}
